In [1]:
# question 1

In [7]:
import numpy as np

In [10]:
list_1=[1,2,3,4,5,6,7,8,9]

In [11]:
arr=np.array(list_1)

In [13]:
type(arr)

numpy.ndarray

In [14]:
type(list_1)

list

In [15]:
# question 2

In [23]:
list_1=[1,2,3,4,5,6,7,8,9]
arr=np.array(list_1)

In [24]:
for i in list_1:
    print(type(i))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [25]:
for i in arr:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [ ]:
# question 3

In [27]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_, dtype=int)

for item in list_:
    print(f"Data type of element in list_: {type(item)}")

for item in array_list:
    print(f"Data type of element in array_list: {type(item)}")

Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>


In [28]:
# question 4

In [33]:
num_list = [[1, 2, 3], [4, 5, 6]]
arr=np.array(num_list)
print(arr)

[[1 2 3]
 [4 5 6]]


In [32]:
np.shape(arr)

(2, 3)

In [34]:
np.size(arr)

6

In [35]:
# question 5

In [39]:
zeromatrix=np.zeros((3,3))

In [40]:
zeromatrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
# question6

In [42]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])